version: "3"
services:
  irango_frontend:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 80:3000
    volumes:
      - .:/home/app/irango_frontend/
      - /home/app/irango_frontend/node_modules
    image: tiagorosadacosta/irango
    command: npm run build
    environment:
      - NODE_ENV: prd
    container_name: irangoFrontend